---
title: "Pulling stations for 2024 IR cycle"
author: "Emma Jones"
date: "6/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pins)
library(config)
library(purrr)
```

Connec to server for pinned data

```{r}

# Server connection things
conn <- config::get("connectionSettings") # get configuration settings


board_register_rsconnect(key = conn$CONNECT_API_KEY,  #Sys.getenv("CONNECT_API_KEY"),
                         server = conn$CONNECT_SERVER)#Sys.getenv("CONNECT_SERVER"))

```

pull monthly assessment data

```{r}
assessment <- pin_get("ejones/statewideResults", board = 'rsconnect')

```


Pull station Table

```{r}

BRROstations <- assessment$BRRO$stationTable
```


find brro stations without WQS

```{r}

filter(BRROstations, is.na(WQS_ID))
```

Do this for all regions (aka your to do list)

```{r}
assessment %>% 
  map_df('stationTable') %>% 
  filter(is.na(WQS_ID))
```


get lat/lng

```{r}
assessment %>% 
  map_df('stationGIS_View') %>% 
  dplyr::select(Station_Id, Latitude, Longitude)
```

join and roll